# Generated by Django 3.2.15 on 2022-09-08 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lms_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='photo_autor',
            new_name='photo_author',
        ),
    ]
